// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from "knex";
import {
  type QueriesInitializer,
  type QueriesMutator,
  type default as Queries,
} from "./public/Queries";
import {
  type DappsInitializer,
  type DappsMutator,
  type default as Dapps,
} from "../models/dapp_analytics/Dapps";

declare module "knex/types/tables" {
  interface Tables {
    queries: Knex.CompositeTableType<
      Queries,
      QueriesInitializer,
      QueriesMutator
    >;
    dapps: Knex.CompositeTableType<Dapps, DappsInitializer, DappsMutator>;
  }
}
