// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from "knex";
import {
  type QueriesInitializer,
  type QueriesMutator,
  type default as Queries,
} from "./public/Queries";
import {
  type DappsInitializer,
  type DappsMutator,
  type default as Dapps,
} from "./dapp_analytics/Dapps";
import {
  type SegmentInitializer,
  type SegmentMutator,
  type default as Segment,
} from "./dapp_analytics/Segment";
import {
  type SegmentMembersInitializer,
  type SegmentMembersMutator,
  type default as SegmentMembers,
} from "./dapp_analytics/SegmentMembers";

declare module "knex/types/tables" {
  interface Tables {
    queries: Knex.CompositeTableType<
      Queries,
      QueriesInitializer,
      QueriesMutator
    >;
    dapps: Knex.CompositeTableType<Dapps, DappsInitializer, DappsMutator>;
    "segment_408f7d49-7ac7-478d-83c7-e2544821dbd4": Knex.CompositeTableType<
      Segment,
      SegmentInitializer,
      SegmentMutator
    >;
    "segment_members_408f7d49-7ac7-478d-83c7-e2544821dbd4": Knex.CompositeTableType<
      SegmentMembers,
      SegmentMembersInitializer,
      SegmentMembersMutator
    >;
  }
}
