// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { Knex } from "knex";
import {
  type QueriesInitializer,
  type QueriesMutator,
  type default as Queries,
} from "./public/Query";

declare module "knex/types/tables" {
  interface Tables {
    queries: Knex.CompositeTableType<
      Queries,
      QueriesInitializer,
      QueriesMutator
    >;
  }
}
