version: "3.8"

services:
  postgres-test:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  db-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8082:8082'
    command: ["sh", "-c", "./wait-for-it.sh postgres-test:5432 -- npm run migrate && npm run watch-node"]
    volumes:
      - .:/usr/src/node-app
    depends_on:
      - postgres-test
    env_file:
      - ./.env.development.local
