version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - EXTRA_DB_NAMES=azero_mainnet_squid,astar_mainnet_squid,crosschain,dapp_analytics
    volumes:
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
  db-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    command: ["npm", "run", "test"]
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - ./.env.test
