version: "3.8"

services:
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  postgres-external:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  db-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8082:8082'
    command: ["sh", "-c", "./wait-for-it.sh postgres-test:5432 -- ./wait-for-it.sh postgres-external:5432 -- npm run migrate && npm run migrate-external && npm run watch-node"]
    volumes:
      - .:/usr/src/node-app
    depends_on:
      - postgres-test
      - postgres-external
    env_file:
      - ./.env.development.local

volumes:
  mongodata:
  dbdata:

networks:
  node-network:
    driver: bridge
