# values for db-api dev environment.
ecrRegistry: 117632573168.dkr.ecr.eu-west-1.amazonaws.com
eksEnvironment: tokenguard-prod

imagePullSecrets: ~

ingressExternal:
  enabled: false

ingressInternal:
  enabled: true
  name: db-api-new-ingress-internal
  rules:
    - host: db-api-new.prod.tokenguard.io       
      http:
        paths:        
        - backend:
            service:
              name: db-api-new
              port:
                number: 8082
          path: /
          pathType: Prefix

dbapi:
  deployment:
    name: db-api-new
    image:
      repository: "tokenguard-prod-db-api"
      pullPolicy: Always
      tag: "2ff1357c6a79485075444b64eb3d94a4b680de6a"
    replicaCount: 1
    env: 
      NODE_ENV: "production"
    resources: 
      requests:
        memory: "256Mi" 
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "2000m"   
  service: 
    name: db-api-new
  configmap:
    name: db-api-new

secrets: 
  name: db-api-new-secrets
