# values for db-api dev environment.
ecrRegistry: 117632573168.dkr.ecr.eu-west-1.amazonaws.com
eksEnvironment: tokenguard-prod

imagePullSecrets: ~

ingressExternal:
  enabled: false

ingressInternal:
  enabled: true
  name: db-api-ingress-internal
  rules:
    - host: db-api.prod.patterns.build
      http:
        paths:
          - backend:
              service:
                name: db-api
                port:
                  number: 8082
            path: /
            pathType: Prefix

dbapi:
  deployment:
    image:
      repository: "tokenguard-prod-db-api"
      pullPolicy: Always
      tag: "f1138de09a2ad15969b8a149cff4f3b2a6d41d9f"
    replicaCount: 1
    env:
      NODE_ENV: "production"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
