// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for dapp_analytics.dapps */
export type DappsId = string & { __brand: "DappsId" };

/** Represents the table dapp_analytics.dapps */
export default interface Dapps {
  id: DappsId;

  name: string;

  logo: string | null;

  blockchain: string;

  website: string | null;

  from_block: string | null;

  added_by: string | null;

  abis: object[];

  created_at: Date | null;

  updated_at: Date | null;

  airdrop_contract: string | null;

  airdrop_currency_contract: string | null;
}

/** Represents the initializer for the table dapp_analytics.dapps */
export interface DappsInitializer {
  /** Default value: uuid_generate_v4() */
  id?: DappsId;

  name: string;

  logo?: string | null;

  blockchain: string;

  website?: string | null;

  from_block?: string | null;

  added_by?: string | null;

  /** Default value: '[]'::jsonb */
  abis?: unknown;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  airdrop_contract?: string | null;

  airdrop_currency_contract?: string | null;
}

/** Represents the mutator for the table dapp_analytics.dapps */
export interface DappsMutator {
  id?: DappsId;

  name?: string;

  logo?: string | null;

  blockchain?: string;

  website?: string | null;

  from_block?: string | null;

  added_by?: string | null;

  abis?: unknown;

  created_at?: Date | null;

  updated_at?: Date | null;

  airdrop_contract?: string | null;

  airdrop_currency_contract?: string | null;
}
