// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for dapp_analytics.dapps */
export type DappsId = number & { __brand: 'DappsId' };

/** Represents the table dapp_analytics.dapps */
export default interface Dapps {
  id: DappsId;

  name: string;

  logo: unknown | null;

  blockchain: string;

  website: string | null;

  from_block: string | null;

  added_by: string | null;

  abis: object[];

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table dapp_analytics.dapps */
export interface DappsInitializer {
  /** Default value: nextval('dapp_analytics.dapps_id_seq'::regclass) */
  id?: DappsId;

  name: string;

  logo?: unknown | null;

  blockchain: string;

  website?: string | null;

  from_block?: string | null;

  added_by?: string | null;

  abis: unknown;

  /** Default value: now() */
  created_at?: Date;

  /** Default value: now() */
  updated_at?: Date;
}

/** Represents the mutator for the table dapp_analytics.dapps */
export interface DappsMutator {
  id?: DappsId;

  name?: string;

  logo?: unknown | null;

  blockchain?: string;

  website?: string | null;

  from_block?: string | null;

  added_by?: string | null;

  abis?: unknown;

  created_at?: Date;

  updated_at?: Date;
}
