// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table dapp_analytics.segment_members_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export default interface SegmentMembers {
  segment_id: string | null;

  dapp_id: string | null;

  user_address: string | null;

  is_airdrop_recipient: boolean | null;

  airdrop_token_address: string | null;

  airdrop_value: string | null;

  first_airdrop_timestamp: Date | null;

  other_dapps_used: string[] | null;

  dapp_first_interaction: Date | null;

  used_functions: string[] | null;

  last_observation: Date | null;
}

/** Represents the initializer for the table dapp_analytics.segment_members_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export interface SegmentMembersInitializer {
  segment_id?: string | null;

  dapp_id?: string | null;

  user_address?: string | null;

  is_airdrop_recipient?: boolean | null;

  airdrop_token_address?: string | null;

  airdrop_value?: string | null;

  first_airdrop_timestamp?: Date | null;

  other_dapps_used?: string[] | null;

  dapp_first_interaction?: Date | null;

  used_functions?: string[] | null;

  last_observation?: Date | null;
}

/** Represents the mutator for the table dapp_analytics.segment_members_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export interface SegmentMembersMutator {
  segment_id?: string | null;

  dapp_id?: string | null;

  user_address?: string | null;

  is_airdrop_recipient?: boolean | null;

  airdrop_token_address?: string | null;

  airdrop_value?: string | null;

  first_airdrop_timestamp?: Date | null;

  other_dapps_used?: string[] | null;

  dapp_first_interaction?: Date | null;

  used_functions?: string[] | null;

  last_observation?: Date | null;
}
