// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table dapp_analytics.segment_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export default interface Segment {
  segment_id: string | null;

  dapp_id: string | null;

  segment_name: string | null;

  creation_timestamp: Date | null;

  members_count: number | null;

  where_statement: string | null;
}

/** Represents the initializer for the table dapp_analytics.segment_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export interface SegmentInitializer {
  segment_id?: string | null;

  dapp_id?: string | null;

  segment_name?: string | null;

  creation_timestamp?: Date | null;

  members_count?: number | null;

  where_statement?: string | null;
}

/** Represents the mutator for the table dapp_analytics.segment_408f7d49-7ac7-478d-83c7-e2544821dbd4 */
export interface SegmentMutator {
  segment_id?: string | null;

  dapp_id?: string | null;

  segment_name?: string | null;

  creation_timestamp?: Date | null;

  members_count?: number | null;

  where_statement?: string | null;
}
