// @generated
// This file is automatically generated. Do not modify manually.

/** Identifier type for public.dapps */
export type DappId = number & { __brand: "DappId" };

/** Represents the table public.dapps */
export default interface Dapp {
  id: DappId;

  name: string;

  slug: string;

  icon: string | null;

  active: boolean;

  dapp_growth_index: boolean;

  defi_growth_index: boolean;

  blockchains: string[] | null;

  created_at: Date | null;

  updated_at: Date | null;
}

/** Represents the initializer for the table public.dapps */
export interface DappInitializer {
  /** Default value: nextval('dapps_id_seq'::regclass) */
  id?: DappId;

  name: string;

  slug: string;

  icon?: string | null;

  active: boolean;

  dapp_growth_index: boolean;

  defi_growth_index: boolean;

  blockchains?: string[] | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;
}

/** Represents the mutator for the table public.dapps */
export interface DappMutator {
  id?: DappId;

  name?: string;

  slug?: string;

  icon?: string | null;

  active?: boolean;

  dapp_growth_index?: boolean;

  defi_growth_index?: boolean;

  blockchains?: string[] | null;

  created_at?: Date | null;

  updated_at?: Date | null;
}
