# values for db-api dev environment.
ecrRegistry: 123622898391.dkr.ecr.eu-west-1.amazonaws.com
eksEnvironment: tokenguard-dev

imagePullSecrets: ~

ingressExternal:
  enabled: false

ingressInternal:
  enabled: true
  name: db-api-ingress-internal
  rules:
    - host: db-api.dev.tokenguard.io       
      http:
        paths:        
        - backend:
            service:
              name: db-api
              port:
                number: 8082
          path: /
          pathType: Prefix

dbapi:
  deployment:
    image:
      repository: "tokenguard-dev-db-api"
      pullPolicy: Always
      tag: "3a4626d1b83624acbfae925fc9ae71da0df890e2"
    replicaCount: 1
    env: 
      NODE_ENV: "development"
    resources: 
      requests:
        memory: "256Mi" 
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "2000m"   

