# values for db-api dev environment.
ecrRegistry: 123622898391.dkr.ecr.eu-west-1.amazonaws.com
eksEnvironment: tokenguard-dev

imagePullSecrets: ~

ingressExternal:
  enabled: false

ingressInternal:
  enabled: true
  name: db-api-new-ingress-internal
  rules:
    - host: db-api-new.dev.patterns.build
      http:
        paths:
          - backend:
              service:
                name: db-api-new
                port:
                  number: 8082
            path: /
            pathType: Prefix

dbapi:
  deployment:
    name: db-api-new
    image:
      repository: "tokenguard-dev-db-api"
      pullPolicy: Always
      tag: "2101c755e0ae8471981561b6e155addfafa4ef2c"
    replicaCount: 1
    env:
      NODE_ENV: "development"
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
  configmap:
    name: db-api-new
  service:
    name: db-api-new

secrets:
  name: db-api-new-secrets
