apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
stringData:
  data-postgres-host: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres-prod/address"
  data-postgres-port: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres-prod/port"
  data-postgres-username: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/data/username"
  data-postgres-password: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/data/password"
  data-postgres-dbnames: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/data/dbnames"
  queries-postgres-host: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres/address"
  queries-postgres-port: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres/port"
  queries-postgres-username: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/queries/username"
  queries-postgres-password: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/queries/password"
  queries-postgres-dbname: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/queries/dbname"
  dapp-analytics-postgres-host: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres/address"
  dapp-analytics-postgres-port: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres/port"
  dapp-analytics-postgres-username: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/dapp-analytics/username"
  dapp-analytics-postgres-password: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/dapp-analytics/password"
  dapp-analytics-postgres-dbname: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/dapp-analytics/dbname"


