{{ if .Values.ingressExternal.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.ingressExternal.name }}
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: {{ .Values.ingressExternal.name }}
spec:
  rules:
{{ toYaml .Values.ingressExternal.rules | indent 4 }}
{{ end }}
