apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.dbapi.service.name }}
  name: {{ .Values.dbapi.service.name }}
spec:
  selector:
    app: {{ .Values.dbapi.service.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
