apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.dbapi.deployment.name }}
  name: {{ .Values.dbapi.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dbapi.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dbapi.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.dbapi.deployment.name }}
          image: "{{ .Values.ecrRegistry }}/{{ .Values.dbapi.deployment.image.repository }}:{{ .Values.dbapi.deployment.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: server-port          
          env:
            - name: PORT
              value: {{ .Values.dbapi.deployment.env.PORT | quote }}                  
            - name: NODE_ENV
              value: {{ .Values.dbapi.deployment.env.NODE_ENV }}
            - name: DATA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: data-postgres-username
            - name: DATA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: data-postgres-password   
            - name: DATA_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: data-postgres-host
            - name: DATA_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: data-postgres-port
            - name: DATA_DB_NAMES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: data-postgres-dbnames
            - name: QUERIES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: queries-postgres-username
            - name: QUERIES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: queries-postgres-password   
            - name: QUERIES_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: queries-postgres-host
            - name: QUERIES_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: queries-postgres-port
            - name: QUERIES_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: queries-postgres-dbname
          resources:
{{ toYaml .Values.dbapi.deployment.resources | indent 12 }}              
          volumeMounts:                           
      volumes:
