{{ if .Values.ingressInternal.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.ingressInternal.name }}
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true" 
  name: {{ .Values.ingressInternal.name }}
spec:
  rules:
{{ toYaml .Values.ingressInternal.rules | indent 4 }}
{{ end }}
