apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
stringData:
  postgres-host: "ref+awsssm://{{ .Values.eksEnvironment }}/infrastructure/rds/postgres-external-prod/address"
  postgres-username: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/username"
  postgres-password: "ref+awsssm://{{ .Values.eksEnvironment }}/application/db-api/db/password"
